### ISSUE TITLE
Tables are not displayed correctly

### ISSUE THREAD

**Issue by manueltuescher** [rtfmkiesel/edubase-downloader#4]
The program does its job, BUT if there are tables in the selected book, these tables are not saved correctly. See picture. 
What can I do so that the tables are displayed correctly? 

![Image](https://github.com/user-attachments/assets/51b71d2a-131d-45fa-8af3-0df211ed1036)

**Comment by rtfmkiesel** [comment]
Hmm this is very weird. The main problem is that I do not have access to a book containing such a table. I've tried with my own books and they look fine. 

If you open this book in the browser, does the table look okay there? (Because I only do automated screenshots of a web page)

Can you try `-c` and point to another Chrome browser? Maybe try Edge if you are on Windows or download a portable Chromium and try chrome.exe from there.

**Comment by manueltuescher** [comment]
Hi :)

First, thank you for your Answer.
The Tables in the Edubase Book on the WebPage looks just right, the allignment is correct.

How do i switch to another browser? Do u have a tutorial or a Doc?

Greetings.
Nachricht von Manu Kiesel ***@***.***> am Apr 22, 2025, 8:15 AM +0200:

**Comment by rtfmkiesel** [comment]
You can use the `-c` parameter to  point to another browser. This needs to be the "chrome.exe" of the other Chrome installation. (or ms-edge.exe)

**Comment by manueltuescher** [comment]
Changed to edge.. and changed to brave browser and at least i tried Ungooled Chromium..

Edge didnt work --> No Login filling.
Brave --> Same Issue with the weird Tables.. 
Ungooled Chromium --> No Login filling.

hmm.. weird.

**Comment by rtfmkiesel** [comment]
Pretty hard to debug without having access to the book.

I've created a 2nd branch called `delaytest`. Can you try it out with this branch? In addition, can you try to increase the page delay with `-d/--delay` to maybe 1 or 1.5 seconds?

**Comment by rtfmkiesel** [comment]
My bad, I was in a hurry and did not test the argument. Should be fixed now.

**Comment by manueltuescher** [comment]
it worked, thx. but the tables are still not correct.. hm :-/

**Comment by rtfmkiesel** [comment]
Sadly there is nothing I can do about that as I do not have access to that book. I downloaded all my books again and all tables are fine. Have you tried other edubase downloaders?

**Comment by manueltuescher** [comment]
i have tried other edubase downloaders. but i always get the error message that the maximum number of pages cannot be read/found. this is the only one that works. i find it strange that the tables are shifted, since it only takes screenshots.

**Comment by manueltuescher** [comment]
i only know 1 other downloader.. this one -> https://github.com/michaelbeutler/edubase-to-pdf

do u know other downloaders?

**Comment by rtfmkiesel** [comment]
I also only know this one, but I have not tried it as I do not use Edubase anymore. Since it uses the same technique, I suspect the tables are also broken there.

If there are only a few pages with broken tables, you could print the page by hand (CTRL+P) while having it open in the Edubase UI. Then stitch the PDF together. (replace the page)

**Comment by rtfmkiesel** [comment]
Thanks for investigating, as I do not have such books.

I see 3 solutions (from best to worst):
+ Detect if a page has such a table and hot patch its style
+ Patch the style globally if this does not break other elements of a book
+ Detect if a page has such a table and use screenshot instead of print

This would need to be implemented and tested by someone who has such a book.

**Comment by manueltuescher** [comment]
@goodygh nice thx, ive tried it.. but its even weirder, the script wont start. have a quick look in the attached video. 
i have to say also, that i've reinstalled my whole System, past Week.. so maybe a bad installation of Python or pip causes this problem. i installed the microsoft store python.. i guess this is wrong?? 

https://github.com/user-attachments/assets/8c7586c6-ec6e-440c-8a54-504744ce7dc5

**Comment by manueltuescher** [comment]
> [@goodygh](https://github.com/goodygh) nice thx, ive tried it.. but its even weirder, the script wont start. have a quick look in the attached video. i have to say also, that i've reinstalled my whole System, past Week.. so maybe a bad installation of Python or pip causes this problem. i installed the microsoft store python.. i guess this is wrong??
> 
>  Unbenanntes.Video.Mit.Clipchamp.erstellt.mp4 
> i reinstalled python / pip.. and installed this tool again with `pip install -r requirements.txt` now i get another weird failure:
> 
> ![Image](https://github.com/user-attachments/assets/e97ae3c6-2651-464a-8617-89a2bec23147)
> 
> the fuck??

i found the mistake.. this tool wont work in PS.. 😂

**Comment by manueltuescher** [comment]
it works perfectly.. :) this tool wasnt build for PowerShell (PS). i had to open it with CMD, now it works like a charm. thank you!

**Comment by manueltuescher** [comment]
the tables displayed correct, with your method. i've noticed no sideeffects yet.. everything seems to be in order. Thank you very much. 
in fact, the PDF contains only Screenshots, then with the linked OCR Repo, the PDF is still searchable. Pretty neat and nice!

**Comment by rtfmkiesel** [comment]
@manueltuescher In my PS env everything works fine. Probably some misconfiguration on your side. 

Thank you both for the help in fixing this.
